#include <random>
#include <fstream>
#include <iostream>
#include <string>
#include <sstream>
#include <cmath>
#include <iomanip>
#include <vector>
#include <algorithm>

class Particle {
    private: 
        double x, mu; 
    
    public:
        int status; // 0 = transmitted, 1 = reflected, 2 = check collision, 3 = absorbed, 4 = travelling

        Particle() : x(0.0), mu(1.0), status(4) {} // Initialize particle at origin, moving in positive direction, status 4 (travelling)

        /*
        int getStatus() const {
            return status;
        }
        */

        void updatePos(double s, double L) { // s is the distance traveled generated by the exponential distribution, L is slab length
            
            x = x + s * mu; // update the position based on the distance traveled and direction

            if (x > L) { // if the particle has traveled beyond the material length
                status = 0; // mark the particle as transmitted
            }
            else if (x < 0) { // if the particle has traveled back beyond the material boundary
                status = 1; // mark the particle as reflected
            }
            else {
                status = 2; // mark the particle as check collision
            }
        } 

        void checkCollision(double c, double u) { // c is the scattering probability, u is the random number generated to determine if a collision occurs
            if (u < c) {
                status = 3; // neutron absorbed 
                std::cout << "Particle absorbed.\n";
            }
            else {
                mu = 2.0 * u - 1.0; // update the direction of the particle after scattering, assuming isotropic scattering in 1D
                status = 4; // particle travelling
                std::cout << "Particle still travelling.\n";
            }
        }
};

class Material {
    private:
        double L; // length of the material
        double c; // probability of scattering
    public:
        Material(double length, double scatterProb) : L(length), c(scatterProb) {
            if (c < 0.0 || c > 1.0) {
                throw std::invalid_argument("Scattering probability must be between 0 and 1.");
            }
            if (L <= 0.0) {
                throw std::invalid_argument("Material length must be positive.");
            }
        }

        double getLength() const {
            return L;
        }

        double getScatteringProbability() const {
            return c;
        }

};

int main() {
    std::random_device rd;
    std::mt19937 engine(rd());
    std::uniform_real_distribution<double> uniform(0.0,1.0); // uniform distribution in the range [0.0, 1.0).    

    double lambda = 1.0; // example value, replace with actual lambda
    double mfp = 1.0 / lambda; // mean free path

    Material material(5.0 * mfp, 0.0); // Create a material with length 5 times the mean free path and scattering probability of 0.5
    Particle particle;

    while (particle.status == 4) { // while the particle is still travelling

        double u = uniform(engine); // generate a random number for the exponential distribution
        while (u <= 0.0) { // ensure u is in (0,1) to avoid log(0)
            u = uniform(engine);
        }
        double freePath = -std::log(u) / lambda; // calculate the distance to the next collision based on the exponential distribution

        particle.updatePos(freePath, material.getLength()); // update the particle's position and status based on the distance traveled


        if (particle.status == 0) {
                std::cout << "Particle transmitted.\n";
            }
            else if (particle.status == 1) {
                std::cout << "Particle reflected.\n";
            }
            else if (particle.status == 2) {
                std::cout << "Particle still in material, check for collision.\n";
                particle.checkCollision(material.getScatteringProbability(), u);

            }
            else if (particle.status == 3) {
                std::cout << "Particle absorbed.\n";
            }
            else if (particle.status == 4) {
                std::cout << "Particle travelling.\n";
            }
        }

        return 0;
}
