#include <random>
#include <fstream>
#include <iostream>
#include <string>
#include <sstream>
#include <cmath>
#include <iomanip>
#include <vector>
#include <algorithm>

class Particle {
    private: 
        double x, mu; 
    
    public:
        int status; // 0 = transmitted, 1 = reflected, 2 = check collision, 3 = absorbed, 4 = travelling

        Particle() : x(0.0), mu(1.0), status(4) {} // Initialize particle at origin, moving in positive direction, status 4 (travelling)

        /*
        int getStatus() const {
            return status;
        }
        */

        void updatePos(double s, double L) { // s is the distance traveled generated by the exponential distribution, L is slab length
            
            x = x + s * mu; // update the position based on the distance traveled and direction

            if (x > L) { // if the particle has traveled beyond the material length
                status = 0; // mark the particle as transmitted
                // std::cout << "Particle transmitted with position: " << x << " and s: " << s << "\n" ; 
            }
            else if (x < 0) { // if the particle has traveled back beyond the material boundary
                status = 1; // mark the particle as reflected
            }
            else {
                status = 2; // mark the particle as check collision
            }
        } 

        void checkCollision(double c, double u) { // c is the scattering probability, u is the random number generated to determine if a collision occurs
            if (u <= c) {
                status = 3; // neutron absorbed 
            }
            else {
                mu = 2.0 * u - 1.0; // update the direction of the particle after scattering, assuming isotropic scattering in 1D
                status = 4; // particle travelling
            }
        }
};

class Material {
    private:
        double L; // length of the material
        double c; // probability of scattering
    public:
        Material(double length, double scatterProb) : L(length), c(scatterProb) {
            if (c < 0.0 || c > 1.0) {
                throw std::invalid_argument("Scattering probability must be between 0 and 1.");
            }
            if (L <= 0.0) {
                throw std::invalid_argument("Material length must be positive.");
            }
        }

        double getLength() const {
            return L;
        }

        double getScatteringProbability() const {
            return c;
        }

};

int main() {
    
    double lambda = 2.0; // example value, replace with actual lambda
    double mfp = 1.0 / lambda; // mean free path

    Material material(5.0 * mfp, 1.0); // Create a material with length 5 times the mean free path and scattering probability of 0.5
    //Particle particle;

    int numSample = 1000; // number of particles to simulate
    std::vector<int> results(3, 0); // vector to store the results of each particle simulation

    // results[0] = number of transmitted particles
    // results[1] = number of reflected particles
    // results[2] = number of absorbed particles

    for (int i = 0; i < numSample; ++i) {

        // Re-seed for each particle to ensure randomness in the simulation
        std::random_device rd;
        std::mt19937 engine(rd());
        std::uniform_real_distribution<double> uniform(0.0,1.0); // uniform distribution in the range [0.0, 1.0).    

        Particle particle = Particle(); // reset particle for each simulation

        while (particle.status == 4) { // while the particle is still travelling

            // --------- Particle propagation ---------
            double u = uniform(engine); // generate a random number for the exponential distribution
            while (u <= 0.0) { // ensure u is in (0,1) to avoid log(0)
                u = uniform(engine);
            }
            double freePath = -std::log(u) / lambda; // calculate the distance to the next collision based on the exponential distribution
            particle.updatePos(freePath, material.getLength()); // update the particle's position and status based on the distance traveled
            // ----------------------------------------

            // --------- Collision handling ---------
            if (particle.status == 0) {
                    //std::cout << "Particle transmitted.\n";
                    results[0]++; // update transmitted count
                }
                else if (particle.status == 1) {
                    //std::cout << "Particle reflected.\n";
                    results[1]++; // update reflected count
                }
                else if (particle.status == 2) {

                    //std::cout << "Particle still in material, check for collision.\n";
                    double u = uniform(engine); // generate a random number for the exponential distribution
                    while (u <= 0.0) { // ensure u is in (0,1) to avoid log(0)
                        u = uniform(engine);
                    }
                    particle.checkCollision(material.getScatteringProbability(), u);

                    if (particle.status == 3) {
                        //std::cout << "Particle absorbed.\n";
                        results[2]++; // update absorbed count
                    }
                    else if (particle.status == 4) {
                        //std::cout << "Particle travelling.\n";
                    }

                }
                else if (particle.status == 3) {
                    //std::cout << "Particle absorbed.\n";
                    results[2]++;
                }
            }
        // ----------------------------------------
    }

    std::cout << "Simulation Results:\n";
    std::cout << "Transmitted: " << results[0] << "\n";
    std::cout << "Reflected: " << results[1] << "\n";
    std::cout << "Absorbed: " << results[2] << "\n";


        return 0;
}
